import { useEffect, useState, type FormEvent } from 'react'
import { Plus } from 'lucide-react'
import { PageHeader } from '@/components/shell/PageHeader'
import { Card } from '@/components/ui/primitives'
import { Modal } from '@/components/ui/Modal'
import { Field } from '@/components/ui/Field'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/app/auth'

interface Cohort { id:string; name:string }; interface Announcement { id:string; title:string; body:string; audience:string|null; cohort_id:string|null; created_at:string }
const audiences=[['','Everyone'],['student','Students'],['trainer','Trainers'],['parent','Parents'],['sponsor','Sponsors'],['manager','Managers']]
export function AnnouncementsPage(){const{role,profile}=useAuth();const canManage=role==='admin'||role==='manager';const[cohorts,setCohorts]=useState<Cohort[]>([]);const[items,setItems]=useState<Announcement[]>([]);const[open,setOpen]=useState(false);const[title,setTitle]=useState('');const[body,setBody]=useState('');const[audience,setAudience]=useState('');const[cohortId,setCohortId]=useState('');const[error,setError]=useState<string|null>(null);const[saving,setSaving]=useState(false)
const load=async()=>{const[c,a]=await Promise.all([supabase.from('cohorts').select('id,name').order('name'),supabase.from('announcements').select('*').order('created_at',{ascending:false})]);const failed=c.error??a.error;if(failed)setError(failed.message);else{setCohorts((c.data??[])as Cohort[]);setItems((a.data??[])as Announcement[])}};useEffect(()=>{load()},[]);const cohort=(id:string|null)=>cohorts.find(c=>c.id===id)?.name;const close=()=>{setOpen(false);setTitle('');setBody('');setAudience('');setCohortId('')};const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError(null);const{error}=await supabase.from('announcements').insert({title:title.trim(),body:body.trim(),audience:audience||null,cohort_id:cohortId||null,created_by:profile?.id});setSaving(false);if(error)setError(error.message);else{close();load()}}
return <div><PageHeader title="Announcements" subtitle="Share updates with the right audience or cohort." actions={canManage?<button onClick={()=>setOpen(true)} className="flex items-center gap-1.5 rounded-[var(--radius-md)] bg-[var(--color-harbor-500)] px-3.5 py-2 text-sm font-semibold text-white"><Plus size={16}/> Create announcement</button>:undefined}/>{error&&<p className="mb-4 rounded-md bg-[var(--color-danger-100)] p-3 text-sm text-[var(--color-danger-600)]">{error}</p>}<Card><ul className="divide-y divide-[var(--color-line)]">{items.length?items.map(item=><li key={item.id} className="p-4"><p className="font-medium text-[var(--color-ink-900)]">{item.title}</p><p className="mt-1 text-sm text-[var(--color-ink-600)]">{item.body}</p><p className="mt-1 text-xs text-[var(--color-ink-400)]">{cohort(item.cohort_id)??(item.audience?`${item.audience} audience`:'Everyone')}</p></li>):<li className="p-8 text-center text-sm text-[var(--color-ink-400)]">No announcements yet.</li>}</ul></Card>{open&&<Modal title="Create announcement" onClose={close}><form onSubmit={save} className="space-y-3"><Field label="Title"><input required className="input" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Message"><textarea required className="input min-h-28" value={body} onChange={e=>setBody(e.target.value)}/></Field><Field label="Audience"><select className="input" value={audience} onChange={e=>setAudience(e.target.value)}>{audiences.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Cohort (optional)"><select className="input" value={cohortId} onChange={e=>setCohortId(e.target.value)}><option value="">All cohorts</option>{cohorts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button disabled={saving} className="rounded-[var(--radius-md)] bg-[var(--color-harbor-500)] px-3.5 py-2 text-sm font-semibold text-white">{saving?'Publishing…':'Publish announcement'}</button></form></Modal>}</div>}
