import { useEffect, useState, type FormEvent } from 'react'
import { Plus } from 'lucide-react'
import { PageHeader } from '@/components/shell/PageHeader'
import { Card } from '@/components/ui/primitives'
import { Modal } from '@/components/ui/Modal'
import { Field } from '@/components/ui/Field'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/app/auth'
import { officialCourses } from '@/lib/courses'

interface Course { id:string; name:string }; interface Cohort { id:string; name:string; course_id:string }; interface Item { id:string; title?:string; topic?:string; cohort_id:string; trainer_id?:string|null; starts_at?:string; due_at?:string|null; status?:string }
export function CourseCohortPage({ kind }: { kind:'sessions'|'assignments'|'projects' }) {
  const {role,profile}=useAuth(); const canManage=['admin','manager','trainer'].includes(role??''); const table=kind==='sessions'?'training_sessions':kind==='assignments'?'assignments':'projects'; const label=kind==='sessions'?'Training Sessions':kind==='assignments'?'Assignments':'Projects'; const [courses,setCourses]=useState<Course[]>([]),[cohorts,setCohorts]=useState<Cohort[]>([]),[trainers,setTrainers]=useState<{id:string;full_name:string}[]>([]),[items,setItems]=useState<Item[]>([]),[open,setOpen]=useState(false),[courseName,setCourseName]=useState(''),[cohortId,setCohortId]=useState(''),[trainerId,setTrainerId]=useState(''),[title,setTitle]=useState(''),[details,setDetails]=useState(''),[date,setDate]=useState(''),[error,setError]=useState<string|null>(null)
  const load=async()=>{const[c,h,t,i]=await Promise.all([supabase.from('courses').select('id,name').order('name'),supabase.from('cohorts').select('id,name,course_id').order('name'),supabase.from('profiles').select('id,full_name').eq('role','trainer').order('full_name'),supabase.from(table).select('*').order('created_at',{ascending:false})]);const failed=c.error??h.error??t.error??i.error;if(failed)setError(failed.message);else{setCourses(officialCourses((c.data??[])as Course[]));setCohorts((h.data??[])as Cohort[]);setTrainers((t.data??[])as {id:string;full_name:string}[]);setItems((i.data??[])as Item[])}};useEffect(()=>{load()},[table]); const selected=courses.find(c=>c.name.toLowerCase()===courseName.trim().toLowerCase());const available=cohorts.filter(c=>c.course_id===selected?.id);const cohort=(id:string)=>cohorts.find(c=>c.id===id);const close=()=>{setOpen(false);setCourseName('');setCohortId('');setTrainerId('');setTitle('');setDetails('');setDate('')};const save=async(e:FormEvent)=>{e.preventDefault();if(!cohortId)return;const result=kind==='sessions'?await supabase.from('training_sessions').insert({topic:title,cohort_id:cohortId,trainer_id:trainerId||null,starts_at:date,status:'scheduled'}):kind==='assignments'?await supabase.from('assignments').insert({title,cohort_id:cohortId,instructions:details||null,due_at:date||null,created_by:profile?.id}):await supabase.from('projects').insert({title,cohort_id:cohortId,description:details||null,due_at:date||null,created_by:profile?.id});if(result.error)setError(result.error.message);else{close();load()}}
  return <div><PageHeader title={label} subtitle={`${kind==='sessions'?'Schedule teaching':'Create learning work'} by course and cohort.`} actions={canManage?<button onClick={()=>setOpen(true)} className="flex items-center gap-1.5 rounded-[var(--radius-md)] bg-[var(--color-harbor-500)] px-3.5 py-2 text-sm font-semibold text-white"><Plus size={16}/> Add {kind==='sessions'?'session':'assignment'}</button>:undefined}/>{error&&<p className="mb-4 text-sm text-[var(--color-danger-600)]">{error}</p>}<Card><ul className="divide-y divide-[var(--color-line)]">{items.length?items.map(i=>{const h=cohort(i.cohort_id);return <li key={i.id} className="p-4"><p className="font-medium text-[var(--color-ink-900)]">{i.topic??i.title}</p><p className="text-sm text-[var(--color-ink-600)]">{h?`${courses.find(c=>c.id===h.course_id)?.name??'Course'} · ${h.name}`:'Cohort'}</p></li>}):<li className="p-8 text-center text-sm text-[var(--color-ink-400)]">No {label.toLowerCase()} found.</li>}</ul></Card>{open&&<Modal title={`Add ${kind==='sessions'?'training session':'assignment'}`} onClose={close}><form onSubmit={save} className="space-y-3"><Field label="Course"><input required list={`${kind}-courses`} className="input" placeholder="Type or choose a course" value={courseName} onChange={e=>{setCourseName(e.target.value);setCohortId('')}}/><datalist id={`${kind}-courses`}>{courses.map(c=><option key={c.id} value={c.name}/>)}</datalist></Field><Field label="Cohort"><select required disabled={!selected||!available.length} className="input" value={cohortId} onChange={e=>setCohortId(e.target.value)}><option value="">{!selected?'Enter a listed course':available.length?'Choose a cohort':'No cohorts for this course'}</option>{available.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{kind==='sessions'&&<Field label="Trainer"><select className="input" value={trainerId} onChange={e=>setTrainerId(e.target.value)}><option value="">Choose a trainer</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></Field>}<Field label={kind==='sessions'?'Topic':'Assignment title'}><input required className="input" value={title} onChange={e=>setTitle(e.target.value)}/></Field>{kind==='assignments'&&<Field label="Instructions"><textarea className="input min-h-24" value={details} onChange={e=>setDetails(e.target.value)}/></Field>}<Field label={kind==='sessions'?'Start time':'Due date'}><input required={kind==='sessions'} type="datetime-local" className="input" value={date} onChange={e=>setDate(e.target.value)}/></Field><button disabled={!cohortId} className="rounded-[var(--radius-md)] bg-[var(--color-harbor-500)] px-3.5 py-2 text-sm font-semibold text-white disabled:opacity-50">Save</button></form></Modal>}</div>
}
